services:
  multiserviciosweb:
    build: ./Back-Soluciones-Webb
    mem_limit: 512m
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - DB_URL=jdbc:postgresql://databasepostgres:5432/${DB_NAME:-SolMaster}
    restart: always
    depends_on:
      databasepostgres:
        condition: service_healthy

  databasepostgres:
    image: postgres:18.1
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      timeout: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql
      - ./SolMaster.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  db_data:
